sudo: required
services:
  -  docker

before_install:
  - docker build -t kristinagenova/react-test -f  ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kristinagenova/react-test npm test

after_success:
  - docker build -t kristinagenova/multi-client ./client
  - docker build -t kristinagenova/multi-nginx ./nginx
  - docker build -t kristinagenova/multi-server ./server
  - docker build -t kristinagenova/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kristinagenova/multi-server
  - docker push kristinagenova/multi-worker
  - docker push kristinagenova/multi-client
  - docker push kristinagenova/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-827948395994
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY